food/urls.py
from django.urls import path
from . import views

app_name="food"
urlpatterns = [
    #shows all items
    path('', views.ItemListView.as_view(), name='index'),
    #empty path
    path('item', views.item, name='item-view'),
    #shows individual items
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-details'),
    #add item
    path('create_item', views.ItemCreateView.as_view(), name='create-item'),
    #edit item
    path('edit_item/<int:id>', views.edit_item, name='edit-item'),
    #delete item
    path('delete_item/<int:id>', views.delete_item, name='delete-item')
]

food_menu/urls.py
from django.contrib import admin
from django.urls import path, include
from food_menu import settings
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.create, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),
]


urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.name

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length = 200)
    desc = models.CharField(max_length = 300)
    price = models.IntegerField()
    image = models.CharField(max_length=500, default = "https://th.bing.com/th/id/OIP.LWunzgdDcx2JtgDBYntqggHaFj?rs=1&pid=ImgDetMain")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('food:item-details', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'desc', 'price', 'image']
    

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import EmailField

class UserForm(UserCreationForm):
    email = EmailField()

    class Meta:
        model =  User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import redirect, render
from django.http import HttpResponse
from food.models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.decorators import login_required
# Create your views here.

# def index(request):
#     items = Item.objects.all()
    
#     context = {
#         'items':items,
#     }
#     return render(request, 'food\index.html', context )

class ItemListView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'items'


def item(request):

    return HttpResponse("<h1>its empty in here </h1>")

class ItemDetailView(DetailView):
    model = Item
    template_name = 'food/details.html'
    context_object_name = 'item'

# def details(request, item_id):
#     item = Item.objects.get(pk=item_id)
#     context = {
#         'item': item,
#     }
#     return render(request, 'food/details.html', context)
    

    
class ItemCreateView(CreateView):
    model = Item
    template_name = 'food/item-form.html'
    fields = ['name', 'desc', 'price', 'image']

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.user = self.request.user
        return super().form_valid(form)


# def create_item(request):
#     #view for creating an item url name (create-item)
#     form = ItemForm(request.POST or None)

#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
    
#     return render(request, 'food/item-form.html', {'form': form})

@login_required
def edit_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if(item.user != request.user):
        from django.http import HttpResponseForbidden
        return HttpResponseForbidden()

    if form.is_valid():
        if(item.user == request.user):
            form.save()
            return redirect('food:index')

    return render(request, 'food/item-form.html', {'form': form})


def delete_item(request,id):

    item = Item.objects.get(id=id)
    if(item.user != request.user):
            from django.http import HttpResponseForbidden
            return HttpResponseForbidden()
    
    if request.method == 'POST':
        if(item.user == request.user):
            item.delete()
            return redirect('food:index')
 


    
    return render(request, 'food/delete-item.html', {'item': item})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserForm
# Create your views here.
def create(request):

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'you have succefully logged in {username} welcome!')
            return redirect('login')
    else:
        form = UserForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous" defer></script>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a href="{% url 'food:index' %}" class="navbar-brand">Foodie</a>

        <ul class="nav">
          <a href="{% url 'food:create-item' %}" class="nav-item nav-link link-light">add an item</a>

          <a href="{% url 'food:index' %}" class="nav-item nav-link link-light">items</a>
          {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <input type="submit" value="logout" class="nav-item nav-link link-light" />
            </form>
          {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link link-light">login</a>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock %}
  </body>
</html>

food/templates/food/delete-item.html
<form method="POST">
  {% csrf_token %}
  <h1>are you sure you want to delete item: {{ item.name }}</h1>
  <button type="submit" class="btn btn-danger">YES</button>
</form>

food/templates/food/details.html
{% extends 'food/base.html' %}

{% block body %}
<div class="card mb-3 mt-3 mx-auto p-2" style="max-width: 800px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="{{item.image}}" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{item.name}}</h5>
          <p class="card-text">{{item.desc}}</p>
          <p class="card-text"><small class="text-body-secondary">${{item.price}}</small></p>
        </div>
      </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Index</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
  </head>
  <body>
    {% block body %}
      {% for item in items %}
        <div class="container">
          <a href="{% url 'food:item-details' item.id %}" class="text-decoration-none">
            <div class="card mb-3 mt-3 mx-auto p-2" style="max-width: 800px;">
              <div class="row g-0">
                <div class="d-flex">
                  <div class="col-md-12">
                    <img src="{{ item.image }}" class="img-thumbnail img-fluid rounded-start" style="height: 250px; width: 250px;" alt="..." />
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <div>
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.desc }}</p>
                        <p class="card-text">
                          <small class="text-body-secondary">${{ item.price }}</small>
                        </p>
                        <p class="card-text">
                          <small class="text-body-secondary">{{ item.user }}</small>
                        </p>
                        <a href="{% url 'food:item-details' item.id %}" class="btn btn-success">view</a>
                        {% if item.user == user %}
                          <a href="{% url 'food:edit-item' item.id %}" class="btn btn-info">Edit</a>
                          <a href="{% url 'food:delete-item' item.id %}" class="btn btn-danger">delete</a>
                        {% else %}

                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a>
        </div>
      {% endfor %}
    {% endblock %}
  </body>
</html>

food/templates/food/item-form.html
{% extends 'food/base.html' %}

{% block body %}
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">add</button>
  </form>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header bg-dark text-white">
            <div class="card-title">login</div>
          </div>
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">{{ field.name }}
                  {{ field }}</div>
              {% endfor %}

              <button type="submit" class="btn btn-dark">login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" alt="img" />

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="card">
          <div class="card-header bg-dark text-white">
            <div class="card-title">register</div>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group">
                  {{ field.name }} <br />
                  {{ field }}
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-dark">register</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% comment %} <form method="post">
  {% csrf_token %}
  {{ form }}
</form> {% endcomment %}